---

- name: Create PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ username }}"
    password: "{{ password }}"
  tags:
    - db

- name: Ensure access to database
  become_user: postgres
  postgresql_privs:
    db: "{{ dbname }}"
    role: "{{ username }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE
  when: dbname is defined
  tags:
    - db

- name: Add Extension
  become_user: postgres
  postgresql_ext:
    name: pg_trgm
    db: "{{ dbname }}"
  when: dbname is defined
  tags:
    - db
